### ISSUE TITLE
Application is not displayed correctly

### ISSUE THREAD

**Issue by mehmetugursoy** [datalogic/scan2deploy-studio#1]
![image](https://user-images.githubusercontent.com/13162984/89176693-aa75a680-d592-11ea-87ef-e3e84571d8fc.png)

As you can see at the attachment , application can't display correctly .

**Comment by codybrookshear** [comment]
Hi,

Wow, haven't seen this one yet. Any chance you have installed "material icons" on your machine possibly (for instance through npm tool)?

What version of Windows are you using (i.e. Windows 10 64 bit?)  anything unusual about your setup?  I assuming you are running Scan2Deploy Studio 1.3?

Thanks!
Cody

**Comment by mehmetugursoy** [comment]
Sorry , I Missed that.  We solved it with Turkey Datalogic Engineer "Semih Guldur" 
That I understand, some icons are downloading from internet, Our company internet is behind the proxy ( Client Proxy is set by Domain Controller)  , and proxy need authorization.  This is why, we had that attached image.

**Comment by codybrookshear** [comment]
Hi again,
Just wanted to let you know that we have released Scan2Deploy Studio v1.4.3 that should address your issue. These icons are now stored local to the application.

https://github.com/datalogic/scan2deploy-studio/releases/tag/v1.4
