### ISSUE TITLE
[Issue]:Datalogic Launcher not configured via Scan2Deploy

### ISSUE THREAD

**Issue by Snik98** [datalogic/scan2deploy-studio#10]
**Describe the bug**
Datalogic Launcher not configured via Scan2Deploy, using the barcode created to autoconfigure the Datalogic Launcher it
does nothing, both with the .cfg file and also with the .tar file.

This happens on a Memor11 with Android 11, PC used is a Windows 10 22H2.

**Comment by zeusin** [comment]
Hey, it seems that datalogic is not offering support on github anymore.

Try on https://discussion.datalogic.com/

**Comment by Pcdejong** [comment]
For the quickest support please create a case on our website:
[https://www.datalogic.com/eng/contact-us/technical-support-cts-8.html](url)

This will give you a quicker answer on these kind of issues. Normally S2D will be perfectly able to configure the Launcher on your Memor 11.
