### ISSUE TITLE
App could not be added on Linux

### ISSUE THREAD

**Issue by woprandi** [datalogic/scan2deploy-studio#2]
I'm unable to select my app to install neither with "add local" or  "add link" button. I have the same error message "App could not be added". It works on Windows

**Comment by abenitezsisteco** [comment]
Same problem here, you can solved?

**Comment by bronson-mock** [comment]
Linux support has been discontinued since the release of Studio v1.8.2. Please use a Windows machine or a dual boot/VM solution.
