### ISSUE TITLE
Latest version 1.7.2 closes right after starting on Windows 11

### ISSUE THREAD

**Issue by jdmerinor** [datalogic/scan2deploy-studio#6]
Hi guys,

I wanted to try the new app 1.7.2 but it just keeps crashing right away after opening it on Windows 11.
I've not tried it on Win 10 but the previous versions of the app used to work just fine on Windows 11.

Please let me know if there is a way you think I can get more info in the nature of the crash.

Thanks.

**Comment by bronson-mock** [comment]
Is this still an issue with the latest 1.9.0 release?

**Comment by jdmerinor** [comment]
it seems to be ok now ;)
