### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by DEV-IDSysMZ** [datalogic/scan2deploy-studio#7]
I got the Following Error when i Exit the App on Windows 10 (Appicon in Infotray->Exit):
```
Uncaught Exception:
Error. connect ECONNREFUSED 127.0.0.1:51070
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
```

Tested older Versions of Scan2Deploy. The Issue does not exist in v1.5.2 but in v1.7.2 and also in v1.8.2

**Comment by bronson-mock** [comment]
Hello, this should be fixed as of version 2.0.0 of Scan2Deploy. Please reopen the issue if encountered again.
